### PR TITLE
Track ziglang/zig:master

### PR DESCRIPTION
**Pull request by jsoref**
⚠️ This PR isn't intended to be merged. I'm going to use it to 🚧 experiment with tracking a live upstream.

At times, I may update the [check-spelling/zig:spell-check](https://github.com/check-spelling/zig/tree/spell-check) branch to reflect the state of the world.

Between when 🛩️ ziglang#9833 was merged and 🛩️ ziglang@87fd502fb68f8f488e6eba6b1f7d70902d6bfe5a, one new library (`nsl`) was added (in ziglang@87fd502fb68f8f488e6eba6b1f7d70902d6bfe5a), which means the spell checker will naturally complain that it doesn't know about it.

This would be fixable by adding `nsl` to `expect.txt` in the `spell-check` branch (the default branch of this repository, which happens to be the merge target for this PR).

If someone creates a PR into `spell-check` for that, I'd probably be willing to merge it (and I'd probably even give them write permissions to this repository to merge on their own). The bot should generate fairly easy to use commands (it's possible they'll be wrong in some cases, including this one, as I think it'll suggest updating the HEAD of the PR, whereas for this case, the thing to update is the BASE of the PR).

### CODE REVIEW

**Comment by andrewrk** [comment]
I got an undesired email notification for this failure and I don't understand why. I didn't subscribe to this repository

**Comment by andrewrk** [comment]
@jsoref please make it stop notifying me

**Comment by andrewrk** [comment]
no offense @jsoref but I am blocking you on github to make it stop notifying me

**Comment by jsoref** [comment]
Ouch, didn't realize it would do that. Sorry. I'm still experimenting with things.

I wonder if "unsubscribe" would have worked, but I'm really not sure.

I guess I'll have to get a couple of users together and experiment to see what does / doesn't work.

**Pull request closed without merging**
